server:
  port: 8881
spring:
  application:
    name: test-service
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8888/user
      prefer-token-info: false
