server:
  port: 8083
spring:
  application:
    name: eureka-client-feign
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15


feign:
  client:
    config:
      feignName:
        # 连接超时时间
        connectTimeout: 5000
        # 读取超时时间
        readTimeout: 5000
        # NONE：不输出日志。
        # BASIC：只输出请求方法的 URL 和响应的状态码以及接口执行的时间。
        # HEADERS：将 BASIC 信息和请求头信息输出。
        # FULL：输出完整的请求信息。
        loggerLevel: full
  # 开启 负载均衡的 熔断
  hystrix:
    enabled: true

logging:
  level:
    com:
      client:
        feign:
          controller: DEBUG