server:
  port: 8081
spring:
  application:
    name: eureka-client-user
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    #注册到Eureka注册中心
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
    # 开启健康检查
#    healthcheck:
#      enabled: true
  instance:
    # 采用IP注册
    prefer-ip-address: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    #  默认 30 秒 每间隔10s，向服务端发送一次心跳，证明自己依然"存活"
    lease-renewal-interval-in-seconds: 5
    #  默认 90 秒 告诉服务端，如果我30s之内没有给你发心跳，就代表我"死"了，将我踢出掉。
    lease-expiration-duration-in-seconds: 15
